FROM python:3.11-slim-bookworm 
RUN apt-get update --fix-missing && apt-get install -y --fix-missing \
    build-essential \
    gcc \
    g++ \
    cmake \
    autoconf && \
    rm -rf /var/lib/apt/lists/* 
RUN pip install chromadb
EXPOSE 8000

CMD ["/usr/local/bin/chroma","run"]