
services:

  weaviate: 
    build: 
      context: ./vector_db
      dockerfile: Dockerfile
    ports: 
      - "8081:8080"
      - "50051:50051"
    environment: 
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=""
      - CLUSTER_HOSTNAME=node1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  ingest: 
    build : ./ingestion
    depends_on: 
      weaviate: 
        condition: service_healthy 
    entrypoint: ["python" , "ingestion.py"]
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - llm

  llm:
    build:
      context: ./vllm
      dockerfile: Dockerfile
    runtime: nvidia
    container_name: llm
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - MODEL_NAME=Qwen/Qwen2.5-3B-Instruct-GPTQ-Int8
      - HUGGING_FACE_HUB_TOKEN=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
    ipc: host
    depends_on:
      weaviate:
        condition: service_healthy


  prometheus: 
    image: prom/prometheus 
    ports: 
      - 9090:9090 
    container_name: prometheus
    volumes: 
      - /home/ubuntu/MLE/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
    
  grafana: 
    image: grafana/grafana 
    ports: 
      - 3000:3000 
    container_name: grafana 
    

  nvidia-dgcm: 
    image: nvcr.io/nvidia/k8s/dcgm-exporter:3.3.9-3.6.1-ubuntu22.04 
    ports: 
      - 9400:9400 
    container_name: nvidia-dgcm 
    runtime: nvidia 
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all 
    cap_add: 
     - SYS_ADMIN
  
  node-exporter: 
    image: prom/node-exporter 
    ports: 
      - 9100:9100
    container_name: node-exporter